Use allowBlocks instead of disallowBlocks
Automattic/crowdsignal-ui pull request #149
Opened 2022-02-04 18:46 UTC by ice9js

This patch updates the editor to use a list of allowed vs. disallowed blocks. This will help us prevent any surprises if new core blocks are added - we don't necessarily want all of them to a be available in the inserter.

The list of currently allowed core blocks:

- buttons
- code
- columns
- group
- heading
- html
- image
- list
- paragraph
- preformatted
- pullquote
- quote
- row
- separator
- spacer
- table
- verse
- video

# Testing

Open the project editor for a new or existing projects and verify only the blocks listed above (and Crowdsignal blocks) are available in the inserter.

2022-02-04 21:00 UTC, jcheringer approved these changes
LGTM!

2022-02-07 12:27 UTC, digitalwaveride requested changes
Left-sidebar library is filtered! Awesome!


### Search still 

Via search... e.g. in the inserter in the editor, I have still access to all the blocks... including not approved ones:

![image](https://user-images.githubusercontent.com/5120357/152786913-c9de24cd-077c-4d07-a938-7653807ebaba.png)


### Quick Block List Update

We should put the "Cover Block" on our list now... as we support the upload now! Great block.

We likely can hide the "verse" block, probably will not see high usage in Crowdsignal context.

2022-02-16 20:12 UTC, CGastrell approved these changes
This is as far as we can get with this, the searcher clearly doesn't honor the disallowed/allowed block list. I'd just add what Thomas suggested and move on with this.

2022-02-23 14:39 UTC, digitalwaveride commented
Happy to move on with this for now! 👍 

... but we will need to come back to this soonish, unfortunately... 😞 - block exploration will be a core onboarding challenge.

2022-02-28 16:22 UTC, merged