Add Twenty-TwentyTwo theme
Automattic/crowdsignal-ui pull request #171
Opened 2022-03-02 22:53 UTC by jcheringer

## Summary

This PR has the necessary adjustments added to the `theme-compatibility` package in order to support the `twenty-twentytwo` theme.

Depends On: D75966-code

Ref: c/UXGxxjdm-tr

## Test Instructions
* Open or create a new project and add some blocks
* On the Editor and on the Project Renderer, add the following param to the URL: `?theme=twentytwentytwo`
* You should see both pages using the new theme style

2022-03-02 22:59 UTC, jcheringer commented
@digitalwaveride I believe I did the necessary adjustments and the theme is looking good.
But I'm counting on your 🦅 👀   to help me in case I missed something.
Thanks! 🙏

2022-03-04 22:43 UTC, digitalwaveride requested changes
Nice João!

Works for me!

Just one little thing I noticed, in the editor it seems as if the styling has impact on the "Project Title":
-> see "Untitled Project" font below:


![image](https://user-images.githubusercontent.com/5120357/156851789-7e01162f-8e44-4696-b41f-5428940a2da4.png)

2022-03-07 20:15 UTC, jcheringer commented
> Nice João!
> 
> Works for me!
> 
> Just one little thing I noticed, in the editor it seems as if the styling has impact on the "Project Title": -> see "Untitled Project" font below:

Hey Thomas, thanks for testing it!
As this issue is something that will affect all new themes implementation, I decided to handle it on a separate PR #177.
The #177, on its own, won't show any difference, since it only increases some CSS selectors' specificity.
The results could be seen on this PR by merging #177 first or, we could merge this PR first and take a look at how the `2022` looks on #177.

2022-03-07 20:41 UTC, CGastrell approved these changes
Works for me!

2022-03-07 20:52 UTC, jcheringer commented
I'm going to merge this PR and we can check if the header issue is solved on #177

2022-03-07 20:53 UTC, merged