Create Themes Modal
Automattic/crowdsignal-ui pull request #179
Opened 2022-03-08 18:44 UTC by jcheringer

TBA

2022-03-11 13:48 UTC, jcheringer commented
Known issues:
* Pages previews, on the left side, are not updating after changing the theme;
* By changing the theme, the `Publish` button should become available to update the Public version theme;

2022-03-14 08:27 UTC, digitalwaveride requested changes
Very very cool João! 😍 
So fun to switch between the themes! 🥳 

### Creation of the project behavior

When creating a new project, the "Theme" section in the Document settings tab is not yet available... neither with an empty project nor with a template as a start.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/5120357/158132193-0cb840fd-8b5d-4143-b528-76a8784681a2.png">

<img width="1787" alt="image" src="https://user-images.githubusercontent.com/5120357/158132377-d54e5140-7931-4c24-9ce9-e703ab7ad87f.png">

Only after saving the draft does it show.
Anything we can do about it?

Wondering how many users would do a "change theme" action very early in the project... or might look for themes area in the very beginning...  


### Modal Window
Two little things I noticed in the modal window... strangely the behavior is always related to which theme is activated:

#### A)

When the TwentyNineteen theme is activated, and only then, the font below the theme previews are not loading correctly 🤷 

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/5120357/158129958-5b5f6cf4-bcf0-4357-a49d-fddbfe7561d5.png">

#### B)

When any other theme besides the Leven theme is activated, the button "Activate this theme" is missing on hover the "hand" the "pointer cursor state".
(pointer appears on these buttons only when Leven theme is activated 🤷 )


### Quadrat Theme

The quadrat is unfortunately not rendering for me ... 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/5120357/158131689-d9cb9e49-e991-46d2-818c-fa86fb4950fa.png">


### Preview Column... 

As you mentioned, the preview column is not adjusting to new theme ... known issue

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/5120357/158131954-f5441d11-9dde-447b-a79e-88a58787ff82.png">



Otherwise, looking good!!!

2022-03-14 20:17 UTC, jcheringer commented
Hey @digitalwaveride, thanks for testing it!
From the issues you reported, I believe I handled all of them, except for the Quadrat theme and the preview column.
The Quadrat PR is still under revision on #178.
And, the preview still needs investigation.
If everything else looks good, I'd suggest handling the preview issue on another PR since this one is already pretty big. 😬

2022-03-14 20:32 UTC, jcheringer commented
The [Publish button issue](https://github.com/Automattic/crowdsignal-ui/pull/179#issuecomment-1065130284) was also fixed.

2022-03-15 14:50 UTC, CGastrell commented
Not sure what's happening, but as soon as the the project attempts a save the editor crashes with this error at the bottom:
<img width="725" alt="image" src="https://user-images.githubusercontent.com/157240/158404154-45517928-36e6-4818-92c5-c925b38695cb.png">

Apparently coming from `<DocumentSettings>` component. Doesn't this happen to you? I applied the backend patch as well

2022-03-15 20:12 UTC, jcheringer commented on apps/project-renderer/src/components/app/index.js
> +	const [ theme, setTheme ] = useState( null );
Well, I think this is something we could explore further.

2022-03-17 12:18 UTC, merged

2022-03-17 12:51 UTC, ice9js commented on apps/project-renderer/src/components/app/index.js
> +	const [ theme, setTheme ] = useState( null );
+1. It does make sense for the project renderer where the themes don't change dynamically.  
That said, we still need something for local testing so probably the best solution is to wrap it up somehow and put it behind one of those `process.env.NODE_ENV === 'production'` flags.