Fix cover block preview
Automattic/crowdsignal-ui pull request #183
Opened 2022-03-11 18:29 UTC by ice9js

This patch fixes page and template previews for full size cover blocks.  
The cover block uses `min-height: 100vh` property to resize itself which works in the browser but was causing issues in the previews where `vh` is based on the current iframe size which is based on the current iframe content - which leads to a race condition and infinite resizing of the iframe.

By putting a cap on the preview height we can prevent it. I choose the same number as used internally by `<BlockPreview />` - unfortunately their fix doesn't quite work in this case.

Note: Because of this, the preview doesn't quite match the editor content in this case but it should be close enough for what it needs to be.

# Testing

- Add a cover block and upload an image. (Or start by adding an image block and converting it to a cover block).
- Select 'Toggle Full Height' from the toolbar and observe the page preview.
- The block should resize just once and stay there compared to continuous enlargement that happened previously.

2022-03-14 05:11 UTC, digitalwaveride requested changes
Nice Kuba!
"Endless zooming" in the previews column is fixed. 👍 
It has issues though fro me with displaying the "full width" characteristic in the previews... 
Feels like the preview supports just "Align Center" (all pages below have cover block Full Width -> .../project/2743672)

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/5120357/158108284-fa5a19f9-783e-46f6-9a68-fbb6120e6495.png">

2022-03-23 17:52 UTC, CGastrell approved these changes
The way I see it, we need to compromise as we can't make a full preview of a too tall page. This should do by now IMHO

2022-03-23 21:07 UTC, digitalwaveride commented
> The way I see it, we need to compromise as we can't make a full preview of a too tall page.

The "windows" in the paging column, should not symbolize a "full-page preview", otherwise these windows can't stay the same height, and the preview windows would be ridiculously long.

The windows should preview a viewport of a "laptop device".
We could show simply the viewport of the top of the page ... the state without scrolling. Everthing that is "below the fold" is not visible in that preview.

2022-04-20 13:28 UTC, ice9js commented
Going to merge it to not hold up what's already fixed any longer.  
As for the full width thing... we need to rebuild the preview component at some point anyway which would be a good opportunity to see if we can address that. As of right now, I don't think 'full width' previews are supported.

2022-04-20 13:28 UTC, merged