Add new project templates
Automattic/crowdsignal-ui pull request #235
Opened 2022-05-10 20:18 UTC by ice9js

This PR enables three new project templates in the new project wizard as well as fixing a few of its style glitches. The new templates include:

- Customer satisfaction survey
- Customer service feedback survey
- Event RSVP form

<img width="708" alt="Screen Shot 2022-05-10 at 10 16 34 PM" src="https://user-images.githubusercontent.com/8056203/167714761-9b685903-111e-4192-8428-45ef7605220d.png">

# Testing

Go to `/project` and verify the new templates are available in the new project wizard and work as expected.

2022-05-12 16:24 UTC, digitalwaveride requested changes
There is a little issue with the "Preview", the rendered view of the first page.
Margins left and right are missing.
Some glitch with the styling of the column block, I guess?


Comparing Editor View 
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/5120357/168122890-c9beca1a-6f25-465a-918d-011f4a8b9e63.png">



and Preview View:

<img width="1401" alt="image" src="https://user-images.githubusercontent.com/5120357/168122748-aed92715-8a4b-414e-8ef7-e4d59b39cf1d.png">

2022-05-13 10:42 UTC, digitalwaveride commented
Maybe related to this? https://github.com/Automattic/crowdsignal-ui/pull/230

2022-05-16 13:57 UTC, ice9js commented
>There is a little issue with the "Preview", the rendered view of the first page.
>Margins left and right are missing.
>Some glitch with the styling of the column block, I guess?

This is an existing issue, not related to these changes and will be addressed separately.

2022-05-16 21:02 UTC, CGastrell commented
The modal looks odd:
<img width="1637" alt="image" src="https://user-images.githubusercontent.com/157240/168681751-a0901dfb-54f6-42af-b23e-d09dc7bee23b.png">

- There should be no scrollbar if there's no need for it
- It's wildly tall for its contents

Need someone to confirm (I've seen my local builds do some crazy things before).

2022-05-17 07:35 UTC, ice9js commented
Rebased & fixed the issue with the scrollbars.

As for why it's so tall... it has to do with how that modal is implemented. It's a 'custom' solution which is not great and the wizard as well as the theme selection modal should be refactored to use the `<Dialog>` component introduced together with the welcome guide in #229.  
Since that's a larger change-set and not really related to adding a new theme, it'll be handled separately.

The only reason why I touched the modal here in the first place was that it was completely broken on smaller screens with a fully populated row (3 items) or even worse when there was more than one row.  
Theme selection modal suffers from similar issues and needs to be fixed as well, but again, that should be done separately by just refactoring these components to use `<Dialog>`.

2022-05-19 12:00 UTC, digitalwaveride approved these changes
👍

2022-05-19 12:01 UTC, merged