Add project state button behavior
Automattic/crowdsignal-ui pull request #63
Opened 2021-10-13 14:58 UTC by CGastrell

This PR adds the necessary state/reducer/action/selector combo so the "Save Draft", "Share" and "Publish/Update" buttons reflect the state of the Project.

`changeProject` action: triggers `PROJECT_CHANGE` with no extra payload for now. Used to reduce to `false` both `isDraftSaved` and `isPublishSaved` so the buttons can enable/disable accordingly

The contents now also carry a timestamp from backend, so this PR should be tested against D68353-code 

NOTE: we could use `select( 'core/block-editor' ).isTyping()` instead/on top of the debounced save for better UX?

## Test instructions
Checkout and run `yarn workspace @crowdsignal/dashboard start`. Use pabtAt-1md-p2 as a guide on button behavior.

2021-10-13 17:23 UTC, ice9js requested changes
Overall, this seems to be the right direction but I left some comments on how to possibly make the code a little more concise.

2021-10-13 17:23 UTC, ice9js commented on apps/dashboard/src/data/action-types.js
> +export const PROJECT_LOADED = 'PROJECT_LOADED';
This doesn't seem to be used anywhere. Let's remove it.

2021-10-13 17:23 UTC, ice9js commented on apps/dashboard/src/data/action-types.js
> +export const PROJECT_CHANGE = 'PROJECT_CHANGE';
This is a little less descriptive than I'd have hoped, can we change it to `PROJECT_STATUS_UPDATE` ?

We can then create an 'enum' for the different status values as required by the frontend, so in addition of updating the actual project object, these could be stored under a separate reducer key.

As for where the enum should go: `/src/util/project/status.js` - we already have some in `/src//util/user/...` if you need a reference.

Suggested values:

`DRAFT`
`DRAFT_WITH_UNSAVED_CHANGES`
`PUBLIC`
`PUBLIC_WITH_UNSAVED_CHANGES`
`PUBLIC_WITH_UNPUBLISHED_CHANGES`

A bit lengthy but I think it gives the right picture. If anything they'll be easy to rename once we start using them.

2021-10-13 17:23 UTC, ice9js commented on apps/dashboard/src/data/projects/reducer.js
> +const isDraftSaved = ( state = false, action ) => {
Like mentioned before, I believe both `isDraftSaved` and `isPublishSaved` could be replaced by a single `status` reducer.  

Note: I think if we go this way this one should best be 'keyed', similar to `items`.

2021-10-14 15:33 UTC, CGastrell commented on apps/dashboard/src/data/projects/reducer.js
> +			action.project.content.published.ts <
I'll see to that on the backend

2021-10-21 14:44 UTC, ice9js commented on .eslintrc
> +			11
😆

2021-10-21 15:40 UTC, merged